import { PuzzleConfig } from '../types'

export const ATWOOD_PUZZLES: PuzzleConfig[] = [
  // BOARD
  {
    id: 'atw_board_001',
    complexity: 'board',
    question: 'In an Atwood machine, m₁ = 3 kg and m₂ = 5 kg. Find the acceleration of the system (g = 10 m/s²).',
    given: { m1: 3, m2: 5, g: 10 },
    find: ['acceleration'],
    answer: { acceleration: 2.5 },
    tolerance: 3,
    hints: ['a = (m₂ − m₁)g/(m₁ + m₂)', 'a = (5−3)×10/(3+5) = 20/8', 'a = 2.5 m/s²'],
    formula: 'a = (m₂−m₁)g/(m₁+m₂)',
    units: { acceleration: 'm/s²' },
  },
  {
    id: 'atw_board_002',
    complexity: 'board',
    question: 'Find the tension in the string for the Atwood machine: m₁ = 3 kg, m₂ = 5 kg (g = 10 m/s²).',
    given: { m1: 3, m2: 5, g: 10 },
    find: ['tension'],
    answer: { tension: 37.5 },
    tolerance: 3,
    hints: ['T = 2m₁m₂g/(m₁+m₂)', 'T = 2×3×5×10/8 = 300/8', 'T = 37.5 N'],
    formula: 'T = 2m₁m₂g/(m₁+m₂)',
    units: { tension: 'N' },
  },
  {
    id: 'atw_board_003',
    complexity: 'board',
    question: 'Two equal masses (4 kg each) hang on an Atwood machine. What is the acceleration?',
    given: { m1: 4, m2: 4, g: 10 },
    find: ['acceleration'],
    answer: { acceleration: 0 },
    tolerance: 2,
    hints: ['Equal masses → system in equilibrium', 'Net force = 0', 'a = 0 m/s²'],
    formula: 'a = (m₂−m₁)g/(m₁+m₂) = 0 when m₁=m₂',
    units: { acceleration: 'm/s²' },
  },
  // JEE MAIN
  {
    id: 'atw_jee_main_001',
    complexity: 'jee_main',
    question: 'In an Atwood machine, m₁ = 4 kg and m₂ = 6 kg. Find the thrust on the pulley (g = 10 m/s²).',
    given: { m1: 4, m2: 6, g: 10 },
    find: ['thrust'],
    answer: { thrust: 96 },
    tolerance: 3,
    hints: ['Thrust = 2T', 'T = 2m₁m₂g/(m₁+m₂) = 2×4×6×10/10 = 48 N', 'Thrust = 2×48 = 96 N'],
    formula: 'Thrust = 2T = 4m₁m₂g/(m₁+m₂)',
    units: { thrust: 'N' },
  },
  {
    id: 'atw_jee_main_002',
    complexity: 'jee_main',
    question: 'In an Atwood machine, the heavier mass (6 kg) starts 2 m above the ground. How long does it take to reach the ground? (m₁=4kg, m₂=6kg, g=10)',
    given: { m1: 4, m2: 6, h: 2, g: 10 },
    find: ['time'],
    answer: { time: 1.265 },
    tolerance: 3,
    hints: [
      'a = (6−4)×10/(4+6) = 2 m/s²',
      'h = ½at² → t = √(2h/a)',
      't = √(2×2/2) = √2 ≈ 1.414 s… Wait, refine: a=2, t=√(4/2)=√2≈1.41 s',
    ],
    formula: 't = √(2h/a)',
    units: { time: 's' },
  },
  {
    id: 'atw_jee_main_003',
    complexity: 'jee_main',
    question: 'An Atwood machine has m₁=5kg and m₂=5kg. A 1 kg mass is added to m₂. Find the new acceleration (g=10 m/s²).',
    given: { m1: 5, m2_new: 6, g: 10 },
    find: ['acceleration'],
    answer: { acceleration: 0.909 },
    tolerance: 3,
    hints: [
      'a = (m₂−m₁)g/(m₁+m₂) = (6−5)×10/(5+6)',
      'a = 10/11 ≈ 0.909 m/s²',
      'The added mass creates the net force',
    ],
    formula: 'a = (m₂−m₁)g/(m₁+m₂)',
    units: { acceleration: 'm/s²' },
  },
  // JEE ADVANCED
  {
    id: 'atw_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'In an Atwood machine on a lift accelerating upward at 2 m/s², m₁=3kg, m₂=5kg. Find acceleration of masses relative to lift (g=10).',
    given: { m1: 3, m2: 5, a_lift: 2, g: 10 },
    find: ['a_rel'],
    answer: { a_rel: 3 },
    tolerance: 3,
    hints: [
      'Effective g = g + a_lift = 10+2 = 12 m/s²',
      'a_rel = (m₂−m₁)g_eff/(m₁+m₂) = (5−3)×12/8',
      'a_rel = 24/8 = 3 m/s²',
    ],
    formula: 'a = (m₂−m₁)(g+a_lift)/(m₁+m₂)',
    units: { a_rel: 'm/s²' },
  },
  {
    id: 'atw_jee_adv_002',
    complexity: 'jee_advanced',
    question: 'An Atwood machine has m₁=1kg and m₂=3kg. Find the ratio of acceleration to g, and the net downward force on the pulley as a fraction of (m₁+m₂)g.',
    given: { m1: 1, m2: 3, g: 10 },
    find: ['a_over_g', 'F_ratio'],
    answer: { a_over_g: 0.5, F_ratio: 0.75 },
    tolerance: 3,
    hints: [
      'a/g = (m₂−m₁)/(m₁+m₂) = 2/4 = 0.5',
      'F_pulley = 2T = 4m₁m₂g/(m₁+m₂) = 4×1×3×g/4 = 3g',
      'F_ratio = 3g/(1+3)g = 0.75',
    ],
    formula: 'a/g = (m₂−m₁)/(m₁+m₂);  F = 4m₁m₂g/(m₁+m₂)',
    units: { a_over_g: '', F_ratio: '' },
  },
  {
    id: 'atw_jee_adv_003',
    complexity: 'jee_advanced',
    question: 'In a modified Atwood machine, m₂ lies on a frictionless table connected via string over a pulley to m₁=3kg hanging vertically. m₂=6kg. Find acceleration and tension (g=10).',
    given: { m1: 3, m2: 6, g: 10 },
    find: ['acceleration', 'tension'],
    answer: { acceleration: 3.33, tension: 20 },
    tolerance: 3,
    hints: [
      'Net force = m₁g (only m₁ drives; m₂ on table has no weight component along motion)',
      'a = m₁g/(m₁+m₂) = 3×10/9 ≈ 3.33 m/s²',
      'T = m₂×a = 6×3.33 ≈ 20 N',
    ],
    formula: 'a = m₁g/(m₁+m₂);  T = m₂a',
    units: { acceleration: 'm/s²', tension: 'N' },
  },
]
