import { PuzzleConfig } from '../types'

export const BOHR_PUZZLES: PuzzleConfig[] = [
  // BOARD
  {
    id: 'bohr_board_001',
    complexity: 'board',
    question: 'Find the radius of the 2nd Bohr orbit of hydrogen (a₀ = 0.529 Å).',
    given: { n: 2, a0: 0.529 },
    find: ['radius'],
    answer: { radius: 2.116 },
    tolerance: 3,
    hints: ['r_n = n² × a₀', 'r₂ = 4 × 0.529', 'r₂ = 2.116 Å'],
    formula: 'r_n = n²a₀',
    units: { radius: 'Å' },
  },
  {
    id: 'bohr_board_002',
    complexity: 'board',
    question: 'Find the energy of the electron in the n = 3 orbit of hydrogen.',
    given: { n: 3 },
    find: ['energy'],
    answer: { energy: -1.51 },
    tolerance: 3,
    hints: ['E_n = −13.6/n² eV', 'E₃ = −13.6/9', 'E₃ ≈ −1.51 eV'],
    formula: 'E_n = −13.6/n² eV',
    units: { energy: 'eV' },
  },
  {
    id: 'bohr_board_003',
    complexity: 'board',
    question: 'What is the wavelength of light emitted in the n=3 → n=2 transition (Balmer series)?',
    given: { n2: 3, n1: 2 },
    find: ['wavelength'],
    answer: { wavelength: 656 },
    tolerance: 3,
    hints: [
      '1/λ = R_H(1/n₁² − 1/n₂²) = 1.097×10⁷(1/4 − 1/9)',
      '= 1.097×10⁷ × 5/36 = 1.524×10⁶ /m',
      'λ = 656 nm (Hα line)',
    ],
    formula: '1/λ = R_H(1/n₁² − 1/n₂²)',
    units: { wavelength: 'nm' },
  },
  // JEE MAIN
  {
    id: 'bohr_jee_main_001',
    complexity: 'jee_main',
    question: 'Find the velocity of an electron in the n=2 orbit of hydrogen (v₁ = 2.18×10⁶ m/s).',
    given: { n: 2, v1: 2.18e6 },
    find: ['velocity'],
    answer: { velocity: 1.09e6 },
    tolerance: 3,
    hints: ['v_n = v₁/n', 'v₂ = 2.18×10⁶/2', 'v₂ = 1.09×10⁶ m/s'],
    formula: 'v_n = v₁/n',
    units: { velocity: 'm/s' },
  },
  {
    id: 'bohr_jee_main_002',
    complexity: 'jee_main',
    question: 'How many emission lines are possible when hydrogen atom transitions from n=4 to n=1?',
    given: { n_high: 4, n_low: 1 },
    find: ['num_lines'],
    answer: { num_lines: 6 },
    tolerance: 1,
    hints: [
      'Total transitions = n(n−1)/2 where n = (n_high − n_low + 1) levels = 4',
      'Lines = 4×3/2 = 6',
      'They are: 4→3, 4→2, 4→1, 3→2, 3→1, 2→1',
    ],
    formula: 'N = n(n-1)/2',
    units: { num_lines: '' },
  },
  {
    id: 'bohr_jee_main_003',
    complexity: 'jee_main',
    question: 'Find the minimum energy photon that can ionise a ground-state hydrogen atom.',
    given: { n: 1, E1: -13.6 },
    find: ['ionisation_energy'],
    answer: { ionisation_energy: 13.6 },
    tolerance: 2,
    hints: ['Ionisation = removing electron to n=∞', 'E_∞ = 0', 'Energy needed = 0 − E₁ = 0 − (−13.6) = 13.6 eV'],
    formula: 'E_ion = −E_1 = 13.6 eV',
    units: { ionisation_energy: 'eV' },
  },
  // JEE ADVANCED
  {
    id: 'bohr_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A hydrogen atom in n=4 de-excites. What is the maximum number of different photon energies that can be emitted?',
    given: { n: 4 },
    find: ['max_photons'],
    answer: { max_photons: 6 },
    tolerance: 1,
    hints: [
      'From n=4: possible transitions to n=1,2,3 → 3 + from n=3 to 1,2 → 2 + from n=2 to 1 → 1',
      'Total = 3+2+1 = 6 different energies',
    ],
    formula: 'N = n(n−1)/2',
    units: { max_photons: '' },
  },
  {
    id: 'bohr_jee_adv_002',
    complexity: 'jee_advanced',
    question: 'A photon of 12.75 eV is absorbed by a ground-state hydrogen atom. To which level is the electron excited?',
    given: { E_photon: 12.75, E1: -13.6 },
    find: ['n_final'],
    answer: { n_final: 4 },
    tolerance: 1,
    hints: [
      'E_final = E₁ + E_photon = −13.6 + 12.75 = −0.85 eV',
      'E_n = −13.6/n² = −0.85 → n² = 13.6/0.85 = 16',
      'n = 4',
    ],
    formula: 'E_n = E_i + E_photon;  n = √(−13.6/E_n)',
    units: { n_final: '' },
  },
  {
    id: 'bohr_jee_adv_003',
    complexity: 'jee_advanced',
    question: 'Find the ratio of kinetic energy to total energy of an electron in the nth Bohr orbit.',
    given: {},
    find: ['ke_to_te_ratio'],
    answer: { ke_to_te_ratio: -1 },
    tolerance: 2,
    hints: [
      'Total energy E_n = −13.6/n² eV (negative)',
      'Kinetic energy KE = +13.6/n² eV (positive, same magnitude)',
      'KE/E_total = (+13.6/n²)/(−13.6/n²) = −1',
    ],
    formula: 'KE = −E_total  (virial theorem for circular orbits)',
    units: { ke_to_te_ratio: '' },
  },
]
