import { PuzzleConfig } from '../types'

export const CIRCULAR_MOTION_PUZZLES: PuzzleConfig[] = [
  {
    id: 'circular_motion_main_0',
    complexity: 'jee_main',
    question: 'A car moving with a speed of $54 \\mathrm{~km} / \\mathrm{h}$ takes a turn of radius 20 m . A simple pendulum is suspended from the ceiling of the car. Determine the angle made by the string of the pendulum with the vertical during the turning. (Take $g=10 \\mathrm{~m} / \\mathrm{s}^2$ ) (JEE Main 2026 (Online) 8th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_1',
    complexity: 'jee_main',
    question: 'A smooth inclined plane ends in a vertical circular loop, as shown in the figure. A small body is released from height $h$ as shown. If the body exerts a force of three times its weight on the plane at the highest point of circle then the height $h=\\alpha R$. The value of $\\alpha$ is $\\_\\_\\_\\_$ (JEE Main 2026 (Online) 6th April Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_2',
    complexity: 'jee_main',
    question: 'A 0.5 kg mass is in contact against the inner wall of a cylindrical drum of radius 4 m rotating about its vertical axis. The minimum rotational speed of the drum to enable the mass to remain stuck to the wall (without falling) is 5 rad/s. The coefficient of friction between the drumâs inner wall surface and mass is _________. (Take $g = 10\\ \\mathrm{m/s^2}$) (JEE Main 2026 (Online) 2nd April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_3',
    complexity: 'jee_main',
    question: 'A particle is rotating in a circular path and at any instant its motion can be described as$\\theta = \\frac{5t^4}{40} - \\frac{t^3}{3}$.The angular acceleration of the particle after 10 seconds is _________ rad/s2. (JEE Main 2026 (Online) 2nd April Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_4',
    complexity: 'jee_main',
    question: 'In case of vertical circular motion of a particle by a thread of length $r$ if the tension in the thread is zero at an angle $30^{\\circ}$ shown in figure, the velocity at the bottom point $(A)$ of the circular path is (g = gravitational acceleration) (JEE Main 2026 (Online) 24th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_5',
    complexity: 'jee_main',
    question: 'A large drum having radius $R$ is spinning around its axis with angular velocity $\\omega$, as shown in figure. The minimum value of $\\omega$ so that a body of mass $M$ remains stuck to the inner wall of the drum, taking the coefficient of friction between the drum surface and mass $M$ as $\\mu$, is : (JEE Main 2026 (Online) 21st January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_6',
    complexity: 'jee_main',
    question: 'Two cars A and B each of mass $10^3$ kg are moving on parallel tracks separated by a distance of 10 m, in same direction with speeds 72 km/h and 36 km/h. The magnitude of angular momentum of car A with respect to car B is ________ JÂ·s. (JEE Main 2026 (Online) 21st January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_7',
    complexity: 'jee_main',
    question: 'A wheel is rolling on a plane surface. The speed of a particle on the highest point of the rim is $8 \\mathrm{~m} / \\mathrm{s}$. The speed of the particle on the rim of the wheel at the same level as the centre of wheel, will be : (JEE Main 2025 (Online) 4th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_8',
    complexity: 'jee_main',
    question: 'A sportsman runs around a circular track of radius $r$ such that he traverses the path $A B A B$. The distance travelled and displacement, respectively, are (JEE Main 2025 (Online) 2nd April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_9',
    complexity: 'jee_main',
    question: 'A body of mass âmâ connected to a massless and unstretchable string goes in vertical circle of radius âRâ under gravity g. The other end of the string is fixed at the center of circle. If velocity at top of circular path is $n\\sqrt{ g R}$ , where, n â¥ 1, then ratio of kinetic energy of the body at bottom to that at top of the circle is : (JEE Main 2025 (Online) 29th January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_10',
    complexity: 'jee_main',
    question: 'A car of mass \' $m$ \' moves on a banked road having radius \' $r$ \' and banking angle $\\theta$. To avoid slipping from banked road, the maximum permissible speed of the car is $v_0$. The coefficient of friction $\\mu$ between the wheels of the car and the banked road is (JEE Main 2025 (Online) 24th January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_11',
    complexity: 'jee_main',
    question: 'A body of mass 100 g is moving in circular path of radius 2 m on vertical plane as shown in figure. The velocity of the body at point $A$ is $10 \\mathrm{~m} / \\mathrm{s}$. The ratio of its kinetic energies at point B and C is :\n\n(Take acceleration due to gravity as $10 \\mathrm{~m} / \\mathrm{s}^2$) (JEE Main 2025 (Online) 22nd January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_12',
    complexity: 'jee_main',
    question: 'A bob of mass $m$ is suspended at a point $O$ by a light string of length $l$ and left to perform vertical motion (circular) as shown in figure. Initially, by applying horizontal velocity $v_0$ at the point \' A \', the string becomes slack when, the bob reaches at the point \' $D$ \'. The ratio of the kinetic energy of the bob at the points B and C is _________. (JEE Main 2025 (Online) 22nd January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_13',
    complexity: 'jee_main',
    question: 'A clock has $$75 \\mathrm{~cm}, 60 \\mathrm{~cm}$$ long second hand and minute hand respectively. In 30 minutes duration the tip of second hand will travel $$x$$ distance more than the tip of minute hand. The value of $$x$$ in meter is nearly (Take $$\\pi=3.14$$) : (JEE Main 2024 (Online) 8th April Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_14',
    complexity: 'jee_main',
    question: 'A car of $$800 \\mathrm{~kg}$$ is taking turn on a banked road of radius $$300 \\mathrm{~m}$$ and angle of banking $$30^{\\circ}$$. If coefficient of static friction is 0.2 then the maximum speed with which car can negotiate the turn safely: $$(\\mathrm{g}=10 \\mathrm{~m} / \\mathrm{s}^2, \\sqrt{3}=1.73)$$ (JEE Main 2024 (Online) 6th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_15',
    complexity: 'jee_main',
    question: 'A man carrying a monkey on his shoulder does cycling smoothly on a circular track of radius $$9 \\mathrm{~m}$$ and completes 120 resolutions in 3 minutes. The magnitude of centripetal acceleration of monkey is (in $$\\mathrm{m} / \\mathrm{s}^2$$ ) : (JEE Main 2024 (Online) 5th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_16',
    complexity: 'jee_main',
    question: 'A cyclist starts from the point $$P$$ of a circular ground of radius $$2 \\mathrm{~km}$$ and travels along its circumference to the point $$\\mathrm{S}$$. The displacement of a cyclist is: (JEE Main 2024 (Online) 4th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_17',
    complexity: 'jee_main',
    question: 'A ball of mass $0.5 \\mathrm{~kg}$ is attached to a string of length $50 \\mathrm{~cm}$. The ball is rotated on a horizontal circular path about its vertical axis. The maximum tension that the string can bear is $400 \\mathrm{~N}$. The maximum possible value of angular velocity of the ball in $\\mathrm{rad} / \\mathrm{s}$ is, : (JEE Main 2024 (Online) 1st February Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_18',
    complexity: 'jee_main',
    question: 'A particle moving in a circle of radius $\\mathrm{R}$ with uniform speed takes time $\\mathrm{T}$ to complete one revolution.\nIf this particle is projected with the same speed at an angle $\\theta$ to the horizontal, the maximum height attained by it is equal to $4 R$. The angle of projection $\\theta$ is then given by : (JEE Main 2024 (Online) 1st February Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_19',
    complexity: 'jee_main',
    question: 'A coin is placed on a disc. The coefficient of friction between the coin and the disc is $$\\mu$$. If the distance of the coin from the center of the disc is $$r$$, the maximum angular velocity which can be given to the disc, so that the coin does not slip away, is : (JEE Main 2024 (Online) 31st January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_20',
    complexity: 'jee_main',
    question: 'A stone of mass $$900 \\mathrm{~g}$$ is tied to a string and moved in a vertical circle of radius $$1 \\mathrm{~m}$$ making $$10 \\mathrm{~rpm}$$. The tension in the string, when the stone is at the lowest point is (if $$\\pi^2=9.8$$ and $$g=9.8 \\mathrm{~m} / \\mathrm{s}^2$$) : (JEE Main 2024 (Online) 29th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_21',
    complexity: 'jee_main',
    question: 'If the radius of curvature of the path of two particles of same mass are in the ratio $$3: 4$$, then in order to have constant centripetal force, their velocities will be in the ratio of : (JEE Main 2024 (Online) 29th January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_22',
    complexity: 'jee_main',
    question: 'A train is moving with a speed of $$12 \\mathrm{~m} / \\mathrm{s}$$ on rails which are $$1.5 \\mathrm{~m}$$ apart. To negotiate a curve radius $$400 \\mathrm{~m}$$, the height by which the outer rail should be raised with respect to the inner rail is (Given, $$g=10 \\mathrm{~m} / \\mathrm{s}^2)$$ : (JEE Main 2024 (Online) 27th January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_23',
    complexity: 'jee_main',
    question: 'A vehicle of mass $$200 \\mathrm{~kg}$$ is moving along a levelled curved road of radius $$70 \\mathrm{~m}$$ with angular velocity of $$0.2 ~\\mathrm{rad} / \\mathrm{s}$$. The centripetal force acting on the vehicle is: (JEE Main 2023 (Online) 13th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_24',
    complexity: 'jee_main',
    question: 'A coin placed on a rotating table just slips when it is placed at a distance of $$1 \\mathrm{~cm}$$ from the center. If the angular velocity of the table in halved, it will just slip when placed at a distance of _________ from the centre : (JEE Main 2023 (Online) 11th April Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_25',
    complexity: 'jee_main',
    question: 'As shown in the figure, a particle is moving with constant speed $$\\pi ~\\mathrm{m} / \\mathrm{s}$$. Considering its motion from $$\\mathrm{A}$$ to $$\\mathrm{B}$$, the magnitude of the average velocity is : (JEE Main 2023 (Online) 6th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_26',
    complexity: 'jee_main',
    question: 'A child of mass $$5 \\mathrm{~kg}$$ is going round a merry-go-round that makes 1 rotation in $$3.14 \\mathrm{~s}$$. The radius of the merry-go-round is $$2 \\mathrm{~m}$$. The centrifugal force on the child will be (JEE Main 2023 (Online) 6th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_27',
    complexity: 'jee_main',
    question: 'A particle is moving with constant speed in a circular path. When the particle turns by an angle $$90^{\\circ}$$, the ratio of instantaneous velocity to its average velocity is $$\\pi: x \\sqrt{2}$$. The value of $$x$$ will be - (JEE Main 2023 (Online) 6th April Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_28',
    complexity: 'jee_main',
    question: 'A small block of mass $$100 \\mathrm{~g}$$ is tied to a spring of spring constant $$7.5 \\mathrm{~N} / \\mathrm{m}$$ and length $$20 \\mathrm{~cm}$$. The other end of spring is fixed at a particular point A. If the block moves in a circular path on a smooth horizontal surface with constant angular velocity $$5 ~\\mathrm{rad} / \\mathrm{s}$$ about point $$\\mathrm{A}$$, then tension in the spring is - (JEE Main 2023 (Online) 6th April Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_29',
    complexity: 'jee_main',
    question: 'A stone of mass $1 \\mathrm{~kg}$ is tied to end of a massless string of length $1 \\mathrm{~m}$. If the breaking tension of the string is $400 \\mathrm{~N}$, then maximum linear velocity, the stone can have without breaking the string, while rotating in horizontal plane, is : (JEE Main 2023 (Online) 31st January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_30',
    complexity: 'jee_main',
    question: 'A body is moving with constant speed, in a circle of radius $10 \\mathrm{~m}$. The body completes one revolution in $4 \\mathrm{~s}$. At the end of 3rd second, the displacement of body (in $\\mathrm{m}$ ) from its starting point is : (JEE Main 2023 (Online) 31st January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_31',
    complexity: 'jee_main',
    question: 'An object moves at a constant speed along a circular path in a horizontal plane with center at the origin. When the object is at $$x=+2~\\mathrm{m}$$, its velocity is $$\\mathrm{ - 4\\widehat j}$$ m/s. The object\'s velocity (v) and acceleration (a) at $$x=-2~\\mathrm{m}$$ will be (JEE Main 2023 (Online) 29th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_32',
    complexity: 'jee_main',
    question: 'A car is moving on a horizontal curved road with radius 50 m. The approximate maximum speed of car will be, if friction between tyres and road is 0.34. [take g = 10 ms$$^{-2}$$] (JEE Main 2023 (Online) 29th January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_33',
    complexity: 'jee_main',
    question: 'A car is moving with a constant speed of 20 m/s in a circular horizontal track of radius 40 m. A bob is suspended from the roof of the car by a massless string. The angle made by the string with the vertical will be : (Take g = 10 m/s$$^2$$) (JEE Main 2023 (Online) 25th January Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_34',
    complexity: 'jee_main',
    question: 'A body of mass 200g is tied to a spring of spring constant 12.5 N/m, while the other end of spring is fixed at point O. If the body moves about O in a circular path on a smooth horizontal surface with constant angular speed 5 rad/s. Then the ratio of extension in the spring to its natural length will be : (JEE Main 2023 (Online) 24th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_35',
    complexity: 'jee_main',
    question: 'A smooth circular groove has a smooth vertical wall as shown in figure. A block of mass m moves against the wall with a speed v. Which of the following curve represents the correct relation between the normal reaction on the block by the wall (N) and speed of the block (v) ? (JEE Main 2022 (Online) 29th July Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_36',
    complexity: 'jee_main',
    question: 'A person moved from A to B on a circular path as shown in figure. If the distance travelled by him is $$60 \\mathrm{~m}$$, then the magnitude of displacement would be :\n(Given $$\\left.\\cos 135^{\\circ}=-0.7\\right)$$ (JEE Main 2022 (Online) 25th July Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_37',
    complexity: 'jee_main',
    question: 'A particle of mass m is moving in a circular path of constant radius r such that its centripetal acceleration (a) is varying with time t as a = k2rt2, where k is a constant. The power delivered to the particle by the force acting on it is given as (JEE Main 2022 (Online) 28th June Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_38',
    complexity: 'jee_main',
    question: 'A stone tide to a spring of length L is whirled in a vertical circle with the other end of the spring at the centre. At a certain instant of time, the stone is at its lowest position and has a speed u. The magnitude of change in its velocity, as it reaches a position where the string is horizontal, is $$\\sqrt {x({u^2} - gL)} $$. The value of x is - (JEE Main 2022 (Online) 27th June Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_39',
    complexity: 'jee_main',
    question: 'A ball is released from rest from point P of a smooth semi-spherical vessel as shown in figure. The ratio of the centripetal force and normal reaction on the ball at point Q is A while angular position of point Q is $$\\alpha$$ with respect to point P. Which of the following graphs represent the correct relation between A and $$\\alpha$$ when ball goes from Q to R? (JEE Main 2022 (Online) 26th June Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_40',
    complexity: 'jee_main',
    question: 'A disc with a flat small bottom beaker placed on it at a distance R from its center is revolving about an axis passing through the center and perpendicular to its plane with an angular velocity $$\\omega$$. The coefficient of static friction between the bottom of the beaker and the surface of the disc is $$\\mu$$. The beaker will revolve with the disc if : (JEE Main 2022 (Online) 25th June Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_41',
    complexity: 'jee_main',
    question: 'For a particle in uniform circular motion, the acceleration $$\\overrightarrow a $$ at any point P(R, $$\\theta$$) on the circular path of radius R is (when $$\\theta$$ is measured from the positive x-axis and v is uniform speed) : (JEE Main 2022 (Online) 25th June Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_42',
    complexity: 'jee_main',
    question: 'A stone of mass m, tied to a string is being whirled in a vertical circle with a uniform speed. The tension in the string is (JEE Main 2022 (Online) 24th June Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_43',
    complexity: 'jee_main',
    question: 'A fly wheel is accelerated uniformly from rest and rotates through 5 rad in the first second. The angle rotated by the fly wheel in the next second, will be : (JEE Main 2022 (Online) 24th June Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_44',
    complexity: 'jee_main',
    question: 'A boy ties a stone of mass 100 g to the end of a 2 m long string and whirls it around in a horizontal plane. The string can withstand the maximum tension of 80 N. If the maximum speed with which the stone can revolve is $${K \\over \\pi }$$ rev./min. The value of K is :\n(Assume the string is massless and unstretchable) (JEE Main 2022 (Online) 24th June Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_45',
    complexity: 'jee_main',
    question: 'A huge circular arc of length 4.4 ly subtends an angle \'4s\' at the centre of the circle. How long it would take for a body to complete 4 revolution if its speed is 8 AU per second?Given : 1 ly = 9.46 $$\\times$$ 1015 m1 AU = 1.5 $$\\times$$ 1011 m (JEE Main 2021 (Online) 27th August Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_46',
    complexity: 'jee_main',
    question: 'A particle of mass m is suspended from a ceiling through a string of length L. The particle moves in a horizontal circle of radius r such that $$r = {L \\over {\\sqrt 2 }}$$. The speed of particle will be : (JEE Main 2021 (Online) 26th August Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_47',
    complexity: 'jee_main',
    question: 'The normal reaction \'N\' for a vehicle of 800 kg mass, negotiating a turn on a 30$$^\\circ$$ banked road at maximum possible speed without skidding is ____________ $$\\times$$ 103 kg m/s2. [Given cos30$$^\\circ$$ = 0.87, $$\\mu$$s = 0.2] (JEE Main 2021 (Online) 20th July Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_48',
    complexity: 'jee_main',
    question: 'A particle of mass m moves in a circular orbit under the central potential field, $$U(r) =  - {C \\over r}$$, where C is a positive constant. The correct radius $$-$$ velocity graph of the particle\'s motion is : (JEE Main 2021 (Online) 18th March Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_49',
    complexity: 'jee_main',
    question: 'A modern grand - prix racing car of mass m is travelling on a flat track in a circular arc of radius R with a speed v. If the coefficient of static friction between the tyres and the track is $$\\mu$$s, then the magnitude of negative lift FL acting downwards on the car is : (Assume forces on the four tyres are identical and g = acceleration due to gravity) (JEE Main 2021 (Online) 17th March Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_50',
    complexity: 'jee_main',
    question: 'Statement I : A cyclist is moving on an unbanked road with a speed of 7 kmh$$-$$1 and takes a sharp circular turn along a path of radius of 2m without reducing the speed. The static friction coefficient is 0.2. The cyclist will not slip and pass the curve. (g = 9.8 m/s2)Statement II : If the road is banked at an angle of 45$$^\\circ$$, cyclist can cross the curve of 2m radius with the speed of 18.5 kmh$$-$$1 without slipping.In the light of the above statements, choose the correct answer from the options given below. (JEE Main 2021 (Online) 16th March Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_51',
    complexity: 'jee_main',
    question: 'A block of 200 g mass moves with a uniform speed in a horizontal circular groove, with vertical side walls of radius 20 cm. If the block takes 40 s to complete one round, the normal force by the side walls of the groove is : (JEE Main 2021 (Online) 16th March Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_52',
    complexity: 'jee_main',
    question: 'A particle is moving with uniform speed along the circumference of a circle of radius R under the action of a central fictitious force F which is inversely proportional to R3. Its time period of revolution will be given by : (JEE Main 2021 (Online) 26th February Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_53',
    complexity: 'jee_main',
    question: 'A clock has a continuously moving second\'s hand of 0.1 m length. The average acceleration of the\ntip of the hand (in units of msâ2) is of the order of : (JEE Main 2020 (Online) 6th September Morning Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_54',
    complexity: 'jee_main',
    question: 'A bead of mass m stays at point P(a, b) on a\nwire bent in the shape of a parabola y = 4Cx2\nand rotating with angular speed $$\\omega $$ (see figure).\nThe value of $$\\omega $$ is (neglect friction) : (JEE Main 2020 (Online) 2nd September Morning Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_55',
    complexity: 'jee_main',
    question: 'A particle of mass m is fixed to one end of a\nlight spring having force constant k and\nunstretched length $$\\ell $$. The other end is fixed. The\nsystem is given an angular speed $$\\omega $$ about the\nfixed end of the spring such that it rotates in a\ncircle in gravity free space. Then the stretch in\nthe spring is : (JEE Main 2020 (Online) 8th January Morning Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_56',
    complexity: 'jee_main',
    question: 'A smooth wire of length 2$$\\pi $$r is bent into a circle and kept in a vertical plane. A bead can slide smoothly on\nthe wire. When the circle is rotating with angular speed $$\\omega $$ about the vertical diameter AB, as shown in figure,\nthe bead is at rest with respect to the circular ring at position P as shown. Then the value of $$\\omega $$2\n is equal to - (JEE Main 2019 (Online) 12th April Evening Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_57',
    complexity: 'jee_main',
    question: 'A body is projected at t = 0 with a velocity 10 msâ1\n at an angle of 60o with the horizontal. The radius of curvature of its trajectory at t = 1s is R. neglecting air resistance and taking acceleration due to gravity g = 10 msâ2, the value of R is : (JEE Main 2019 (Online) 11th January Morning Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_58',
    complexity: 'jee_main',
    question: 'A particle is moving along a circular path with a constant speed of 10 msâ1. What is the magnitude of the change in velocity of the particle, when it moves through an angle of 60o around the centre of the circle? (JEE Main 2019 (Online) 11th January Morning Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_59',
    complexity: 'jee_main',
    question: 'A disc rotates about its axis of symmetry in a horizontal plane at a steady rate of $$3.5$$ revolutions per second. A coin placed at a distnce of 1.25 cm from the axis of rotation remains at rest on the disc. The coefficient of friction between the coin and the disc is : (g = 10 m/s2) (JEE Main 2018 (Online) 15th April Evening Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_60',
    complexity: 'jee_main',
    question: 'A conical pendulum of length 1 m makes an angle $$\\theta $$ = 45o w.r.t. Z-axis and moves in a circle in the XY plane. The radius of the circle is 0.4 m and its center is vertically below O. The speed of the pendulum, in its circular path, will be: (Take g = 10 msâ2 ) (JEE Main 2017 (Online) 9th April Morning Slot)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_61',
    complexity: 'jee_main',
    question: 'Two cars of masses m1 and m2 are moving in circles of radii r1 and r2, respectively. Their speeds are such that they make complete circles in the same time t. The ratio of their centripetal acceleration is (AIEEE 2012)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_62',
    complexity: 'jee_main',
    question: 'For a particle in uniform circular motion the acceleration $$\\overrightarrow a $$ at a point P(R, Î¸) on the circle of radius R is (here Î¸ is measured from the xâaxis) (AIEEE 2010)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_63',
    complexity: 'jee_main',
    question: 'A point $$P$$ moves in counter-clockwise direction on a circular path as shown in the figure. The movement of $$P$$ is such that it sweeps out a length $$s = {t^3} + 5,$$ where $$s$$ is in metres and $$t$$ is in seconds. The radius of the path is $$20$$ $$m.$$ The acceleration of $$\'P\'$$ when $$t=2$$ $$s$$ is nearly. (AIEEE 2010)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_64',
    complexity: 'jee_main',
    question: 'Which of the following statements is FALSE for a particle moving in a circle with a constant\nangular speed? (AIEEE 2004)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_65',
    complexity: 'jee_main',
    question: 'The minimum velocity (in $$m{s^{ - 1}}$$) with which a car driver must traverse a flat curve of radius 150 m and coefficient of friction $$0.6$$ to avoid skidding is (AIEEE 2002)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_66',
    complexity: 'jee_main',
    question: 'A particle of charge $1.6 \\mu \\mathrm{C}$ and mass $16 \\mu \\mathrm{~g}$ is present in a strong magnetic field of 6.28 T . The particle is then fired perpendicular to magnetic field. The time required for the particle to return to original location for the first time is _________ s. $(\\pi=3.14)$ (JEE Main 2025 (Online) 4th April Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_67',
    complexity: 'jee_main',
    question: 'A string of length $L$ is fixed at one end and carries a mass of $M$ at the other end. The mass makes $\\left(\\frac{3}{\\pi}\\right)$ rotations per second about the vertical axis passing through end of the string as shown. The tension in the string is __________ ML. (JEE Main 2025 (Online) 24th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_68',
    complexity: 'jee_main',
    question: 'A tube of length 1 m is filled completely with an ideal liquid of mass 2 M , and closed at both ends. The tube is rotated uniformly in horizontal plane about one of its ends. If the force exerted by the liquid at the other end is F then angular velocity of the tube is $\\sqrt{\\frac{\\mathrm{F}}{\\alpha \\mathrm{M}}}$ in SI unit. The value of $\\alpha$ is _________. (JEE Main 2025 (Online) 22nd January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_69',
    complexity: 'jee_main',
    question: 'A particle is moving in a circle of radius $$50 \\mathrm{~cm}$$ in such a way that at any instant the normal and tangential components of it\'s acceleration are equal. If its speed at $$\\mathrm{t}=0$$ is $$4 \\mathrm{~m} / \\mathrm{s}$$, the time taken to complete the first revolution will be $$\\frac{1}{\\alpha}\\left[1-e^{-2 \\pi}\\right] \\mathrm{s}$$, where $$\\alpha=$$ _________. (JEE Main 2024 (Online) 29th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_70',
    complexity: 'jee_main',
    question: 'A stone tied to $180 \\mathrm{~cm}$ long string at its end is making 28 revolutions in horizontal circle in every minute. The magnitude of acceleration of stone is $\\frac{1936}{x} ms^{-2}$. The value of $x$ ________. (Take $\\pi=\\frac{22}{7}$ ) (JEE Main 2023 (Online) 30th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_71',
    complexity: 'jee_main',
    question: 'A car is moving on a circular path of radius 600 m such that the magnitudes of the tangential acceleration and centripetal acceleration are equal. The time taken by the car to complete first quarter of revolution, if it is moving with an initial speed of 54 km/hr is $$t(1-e^{-\\pi/2})s$$. The value of t is ____________. (JEE Main 2023 (Online) 29th January Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_72',
    complexity: 'jee_main',
    question: 'A person starts his journey from centre \'O\' of the park and comes back to the same position following path OPQO as shown in the figure. The radius of path taken by the person is 200 m and he takes 3 min 58 sec to complete his journey. The average speed of the person is _____________ ms$$-$$1. (take $$\\pi$$ = 3.14) (JEE Main 2022 (Online) 30th June Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_73',
    complexity: 'jee_main',
    question: 'A pendulum of length 2 m consists of a wooden bob of mass 50 g. A bullet of mass 75 g is fired towards the stationary bob with a speed v. The bullet emerges out of the bob with a speed $${v \\over 3}$$ and the bob just completes the vertical circle. The value of v is ___________ ms$$-$$1. (if g = 10 m/s2). (JEE Main 2022 (Online) 27th June Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_74',
    complexity: 'jee_main',
    question: 'A curved in a level road has a radius 75 m. The maximum speed of a car turning this curved road can be 30 m/s without skidding. If radius of curved road is changed to 48 m and the coefficient of friction between the tyres and the road remains same, then maximum allowed speed would be ___________ m/s. (JEE Main 2022 (Online) 25th June Evening Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  },
  {
    id: 'circular_motion_main_75',
    complexity: 'jee_main',
    question: 'A small bob tied at one end of a thin string of length 1 m is describing a vertical circle so that the maximum and minimum tension in the string are in the ratio 5 : 1. The velocity of the bob at the highest position is ________ m/s. (Take g = 10 m/s2) (JEE Main 2021 (Online) 25th February Morning Shift)',
    given: {},
    find: ['answer'],
    answer: { answer: 0 },
    tolerance: 5,
    hints: ['Refer to original text for values.'],
    formula: 'N/A',
    units: { answer: '' }
  }
]