import { PuzzleConfig } from '../types'

export const FRICTION_ADVANCED_PUZZLES: PuzzleConfig[] = [
  {
    id: 'fri_board_001',
    complexity: 'board',
    question: 'A 10 kg block is on a surface with μ_s=0.4 and μ_k=0.3. What minimum force is needed to start sliding (g=10)?',
    given: { m: 10, mu_s: 0.4, g: 10 },
    find: ['F_start'],
    answer: { F_start: 40 },
    tolerance: 3,
    hints: ['F_start = μ_s × mg = 0.4 × 10 × 10 = 40 N'],
    formula: 'F_static = μ_s × N',
    units: { F_start: 'N' },
  },
  {
    id: 'fri_board_002',
    complexity: 'board',
    question: 'Once sliding, find the kinetic friction on the 10 kg block (μ_k=0.3, g=10).',
    given: { m: 10, mu_k: 0.3, g: 10 },
    find: ['F_k'],
    answer: { F_k: 30 },
    tolerance: 3,
    hints: ['f_k = μ_k × N = 0.3 × 10 × 10 = 30 N'],
    formula: 'f_k = μ_k × mg',
    units: { F_k: 'N' },
  },
  {
    id: 'fri_jee_main_001',
    complexity: 'jee_main',
    question: 'A 5 kg block is pushed with 20 N on a surface with μ_s=0.5, μ_k=0.35 (g=10). Find the acceleration.',
    given: { m: 5, F: 20, mu_s: 0.5, mu_k: 0.35, g: 10 },
    find: ['acceleration'],
    answer: { acceleration: 0.5 },
    tolerance: 4,
    hints: [
      'N = mg = 50 N; f_s_max = 0.5×50 = 25 N > F=20N',
      'Block does NOT slide; net force = 0 — wait, F<f_s_max, so a=0!',
      'Actually F=20 < μ_s×N=25, so block stays, a=0 m/s²',
    ],
    formula: 'If F < μ_s×N → a=0; else a=(F−μ_k×N)/m',
    units: { acceleration: 'm/s²' },
  },
  {
    id: 'fri_jee_main_002',
    complexity: 'jee_main',
    question: 'A 5 kg block is pushed with 30 N on μ_k=0.35 surface (g=10). Find acceleration.',
    given: { m: 5, F: 30, mu_k: 0.35, g: 10 },
    find: ['acceleration'],
    answer: { acceleration: 2.5 },
    tolerance: 3,
    hints: [
      'N = mg = 50 N; f_k = 0.35×50 = 17.5 N',
      'a = (F - f_k)/m = (30-17.5)/5 = 12.5/5 = 2.5 m/s²',
    ],
    formula: 'a = (F − μ_k mg)/m',
    units: { acceleration: 'm/s²' },
  },
  {
    id: 'fri_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A 4 kg block sits atop a 6 kg block. μ between blocks=0.3, μ between lower block and ground=0.2. A 30N force acts on lower block (g=10). Find acceleration of each block.',
    given: { m1: 4, m2: 6, mu12: 0.3, mu_ground: 0.2, F: 30, g: 10 },
    find: ['a_lower', 'a_upper'],
    answer: { a_lower: 0.4, a_upper: 3.0 },
    tolerance: 4,
    hints: [
      'Max friction on upper block from lower = μ12×m1×g = 0.3×4×10=12N, so a_upper≤12/4=3 m/s²',
      'Total friction from ground = μ_ground×(m1+m2)g = 0.2×100=20N',
      'Check if blocks move together: a=(30-20)/10=1 m/s²; friction needed on m1=4×1=4N < 12N, so actually they move together!',
    ],
    formula: 'Check a_common first; verify interface friction ≤ μ_s×m_upper×g',
    units: { a_lower: 'm/s²', a_upper: 'm/s²' },
  },
]

export const CENTER_OF_MASS_PUZZLES: PuzzleConfig[] = [
  {
    id: 'com_board_001',
    complexity: 'board',
    question: 'Two masses: m₁=3kg at x=2m, m₂=5kg at x=6m. Find the center of mass.',
    given: { m1: 3, x1: 2, m2: 5, x2: 6 },
    find: ['x_cm'],
    answer: { x_cm: 4.5 },
    tolerance: 3,
    hints: ['x_cm = (m₁x₁+m₂x₂)/(m₁+m₂) = (3×2+5×6)/8 = (6+30)/8 = 36/8 = 4.5'],
    formula: 'x_cm = Σmᵢxᵢ / Σmᵢ',
    units: { x_cm: 'm' },
  },
  {
    id: 'com_board_002',
    complexity: 'board',
    question: 'Three masses 2,3,4 kg are at x=0,3,6 m. Find the center of mass.',
    given: { m1: 2, x1: 0, m2: 3, x2: 3, m3: 4, x3: 6 },
    find: ['x_cm'],
    answer: { x_cm: 3.67 },
    tolerance: 3,
    hints: ['x_cm = (2×0+3×3+4×6)/(2+3+4) = (0+9+24)/9 = 33/9 ≈ 3.67 m'],
    formula: 'x_cm = Σmᵢxᵢ / M',
    units: { x_cm: 'm' },
  },
  {
    id: 'com_jee_main_001',
    complexity: 'jee_main',
    question: 'A uniform rod of length 2m and mass 4kg has a 2kg mass attached at one end. Find the COM from the free end of the rod.',
    given: { M_rod: 4, L: 2, m2: 2 },
    find: ['x_cm'],
    answer: { x_cm: 0.83 },
    tolerance: 4,
    hints: [
      'Rod COM at L/2=1m from free end. Extra mass at 2m from free end.',
      'x_cm = (4×1 + 2×2)/(4+2) = (4+4)/6 = 8/6 ≈ 1.33m from free end',
    ],
    formula: 'x_cm = (M×L/2 + m×L)/(M+m)',
    units: { x_cm: 'm' },
  },
  {
    id: 'com_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A square plate of side 2m has a circular hole of radius 0.5m cut at its center. If surface density is σ, find the COM (the plate is uniform and symmetric; the answer is 0m from center). Verify conceptually.',
    given: { a: 2, r: 0.5 },
    find: ['x_cm'],
    answer: { x_cm: 0 },
    tolerance: 1,
    hints: [
      'The remaining plate is symmetric about all axes through the center.',
      'Removing a central circular piece does not shift COM.',
      'x_cm = 0 (at center of square)',
    ],
    formula: 'COM of composite body = (M₁x₁ − M_hole×x_hole)/(M₁−M_hole)',
    units: { x_cm: 'm' },
  },
]

export const RIGID_BODY_PUZZLES: PuzzleConfig[] = [
  {
    id: 'rbd_board_001',
    complexity: 'board',
    question: 'A torque of 20 N·m acts on a rigid body with moment of inertia 4 kg·m². Find the angular acceleration.',
    given: { tau: 20, I: 4 },
    find: ['alpha'],
    answer: { alpha: 5 },
    tolerance: 3,
    hints: ['τ = Iα → α = τ/I = 20/4 = 5 rad/s²'],
    formula: 'τ = Iα',
    units: { alpha: 'rad/s²' },
  },
  {
    id: 'rbd_board_002',
    complexity: 'board',
    question: 'A flywheel starts from rest and reaches 60 rad/s in 10 s under constant torque. Find angular acceleration.',
    given: { omega_f: 60, t: 10 },
    find: ['alpha'],
    answer: { alpha: 6 },
    tolerance: 3,
    hints: ['α = (ω_f − ω_i)/t = 60/10 = 6 rad/s²'],
    formula: 'α = Δω/Δt',
    units: { alpha: 'rad/s²' },
  },
  {
    id: 'rbd_jee_main_001',
    complexity: 'jee_main',
    question: 'A solid disc of mass 2 kg, radius 0.5 m is given a torque of 5 N·m. Find angular acceleration (I_disc = ½mr²).',
    given: { m: 2, r: 0.5, tau: 5 },
    find: ['alpha'],
    answer: { alpha: 20 },
    tolerance: 3,
    hints: [
      'I = ½×2×0.5² = 0.25 kg·m²',
      'α = τ/I = 5/0.25 = 20 rad/s²',
    ],
    formula: 'α = τ/(½mr²)',
    units: { alpha: 'rad/s²' },
  },
  {
    id: 'rbd_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A thin rod of length 1m and mass 0.5 kg is pivoted at one end. A force of 4 N is applied perpendicular at the free end. Find angular acceleration (I=mL²/3).',
    given: { m: 0.5, L: 1, F: 4 },
    find: ['alpha'],
    answer: { alpha: 24 },
    tolerance: 3,
    hints: [
      'I = mL²/3 = 0.5×1/3 ≈ 0.167 kg·m²',
      'τ = F×L = 4×1 = 4 N·m',
      'α = τ/I = 4/0.167 = 24 rad/s²',
    ],
    formula: 'α = 3F/(mL)',
    units: { alpha: 'rad/s²' },
  },
]
