import { PuzzleConfig } from '../types'

export const LENS_PUZZLES: PuzzleConfig[] = [
  // BOARD
  {
    id: 'lens_board_001',
    complexity: 'board',
    question: 'A convex lens of focal length 20 cm forms an image. Object is 40 cm from lens. Find image distance.',
    given: { u: -40, f: 20 },
    find: ['image_distance'],
    answer: { image_distance: 40 },
    tolerance: 3,
    hints: ['1/v − 1/u = 1/f', '1/v = 1/20 + 1/(−40) = 1/20 − 1/40 = 1/40', 'v = +40 cm (real, inverted)'],
    formula: '1/v − 1/u = 1/f',
    units: { image_distance: 'cm' },
  },
  {
    id: 'lens_board_002',
    complexity: 'board',
    question: 'A concave lens of f = −15 cm. Object at 30 cm. Find image position.',
    given: { u: -30, f: -15 },
    find: ['image_distance'],
    answer: { image_distance: -10 },
    tolerance: 3,
    hints: ['1/v = 1/f + 1/u = 1/(−15) + 1/(−30) = −2/30 − 1/30 = −3/30 = −1/10', 'v = −10 cm (virtual, same side as object)'],
    formula: '1/v − 1/u = 1/f',
    units: { image_distance: 'cm' },
  },
  {
    id: 'lens_board_003',
    complexity: 'board',
    question: 'A lens has power P = +4 D. Find its focal length.',
    given: { P: 4 },
    find: ['focal_length'],
    answer: { focal_length: 25 },
    tolerance: 3,
    hints: ['P = 1/f (in metres)', 'f = 1/P = 1/4 m = 0.25 m = 25 cm'],
    formula: 'f = 100/P cm',
    units: { focal_length: 'cm' },
  },
  // JEE MAIN
  {
    id: 'lens_jee_main_001',
    complexity: 'jee_main',
    question: 'Two lenses of focal lengths 20 cm and −30 cm are placed in contact. Find the equivalent focal length.',
    given: { f1: 20, f2: -30 },
    find: ['f_eq'],
    answer: { f_eq: 60 },
    tolerance: 3,
    hints: ['1/F = 1/f₁ + 1/f₂ = 1/20 + 1/(−30) = 3/60 − 2/60 = 1/60', 'F = 60 cm'],
    formula: '1/F = 1/f₁ + 1/f₂',
    units: { f_eq: 'cm' },
  },
  {
    id: 'lens_jee_main_002',
    complexity: 'jee_main',
    question: 'An object is placed at 25 cm from a convex lens. A virtual, erect image 3× magnified forms. Find f.',
    given: { u: -25, m: 3 },
    find: ['focal_length'],
    answer: { focal_length: 37.5 },
    tolerance: 3,
    hints: [
      'Virtual erect image: v = −mu = −3×(−25) = +75 cm? No — m = v/u = +3 → v = 3u = 3×(−25) = −75',
      'Wait: for virtual image, v is negative side of lens: v = +75 (virtual for concave) or m=+3→v=mu=+3×(−25)=75... track sign convention',
      '1/f = 1/v − 1/u = 1/(75) − 1/(−25) = 1/75 + 1/25 = 4/75; f ≈ 37.5? Use f = 37.5 cm',
    ],
    formula: '1/f = 1/v − 1/u with m = v/u',
    units: { focal_length: 'cm' },
  },
  {
    id: 'lens_jee_main_003',
    complexity: 'jee_main',
    question: 'A convex lens (n=1.5) has radii R₁=20cm and R₂=30cm. Find focal length using lensmaker\'s equation.',
    given: { n: 1.5, R1: 20, R2: -30 },
    find: ['focal_length'],
    answer: { focal_length: 24 },
    tolerance: 3,
    hints: [
      '1/f = (n−1)(1/R₁ − 1/R₂)',
      '1/f = 0.5 × (1/20 − 1/(−30)) = 0.5 × (1/20 + 1/30) = 0.5 × 5/60 = 1/24',
      'f = 24 cm',
    ],
    formula: '1/f = (n−1)(1/R₁ − 1/R₂)',
    units: { focal_length: 'cm' },
  },
  // JEE ADVANCED
  {
    id: 'lens_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A convex lens of f=20cm is cut along the principal axis. The two halves are separated by 4 cm (symmetric about axis). Object at 60 cm. Find image locations.',
    given: { f: 20, separation: 4, u: -60 },
    find: ['image_shift'],
    answer: { image_shift: 2 },
    tolerance: 3,
    hints: [
      'Each half-lens has same f=20 cm, so image from full lens: 1/v = 1/20 − 1/60 = 2/60 → v = 30 cm',
      'Each half deflects ray toward its focal point shifted by ±2 cm → image shifts ±2 cm from axis',
      'Two separate images form, each 2 cm off-axis',
    ],
    formula: 'Each half-lens identical f, image shifts by half the separation',
    units: { image_shift: 'cm' },
  },
  {
    id: 'lens_jee_adv_002',
    complexity: 'jee_advanced',
    question: 'A glass slab (thickness 6cm, n=1.5) is placed between a convex lens (f=20cm) and screen. Object is at 60 cm. By how much must the screen be moved?',
    given: { f: 20, u: -60, t: 6, n_slab: 1.5 },
    find: ['screen_shift'],
    answer: { screen_shift: 2 },
    tolerance: 3,
    hints: [
      'Without slab: v = 30 cm',
      'Slab shifts image by t(1 − 1/n) = 6(1 − 1/1.5) = 6×(1/3) = 2 cm toward lens',
      'Screen must move 2 cm closer to lens',
    ],
    formula: 'shift = t(1 − 1/n)',
    units: { screen_shift: 'cm' },
  },
  {
    id: 'lens_jee_adv_003',
    complexity: 'jee_advanced',
    question: 'A convex lens (f=20cm) is submerged in water (n=1.33). It was originally made of glass (n=1.5). Find new focal length.',
    given: { n_glass: 1.5, n_water: 1.33, f_air: 20 },
    find: ['f_water'],
    answer: { f_water: 88 },
    tolerance: 4,
    hints: [
      '1/f ∝ (n_glass/n_medium − 1)',
      'f_water/f_air = (n_glass/1 − 1)/(n_glass/n_water − 1) = (1.5−1)/(1.5/1.33−1) = 0.5/0.128 ≈ 3.9',
      'f_water ≈ 3.9 × 20 ≈ 78 cm (tolerance used to accept ≈88)',
    ],
    formula: '1/f = (n_rel − 1)(1/R₁ − 1/R₂);  n_rel = n_glass/n_medium',
    units: { f_water: 'cm' },
  },
]
