import { PuzzleConfig } from '../types'

export const MIRROR_PUZZLES: PuzzleConfig[] = [
  // BOARD
  {
    id: 'mir_board_001',
    complexity: 'board',
    question: 'An object is placed 30 cm in front of a concave mirror of focal length 15 cm. Find the image distance.',
    given: { u: -30, f: -15 },
    find: ['image_distance'],
    answer: { image_distance: -30 },
    tolerance: 3,
    hints: ['1/v + 1/u = 1/f', '1/v = 1/f − 1/u = 1/(−15) − 1/(−30) = −1/15 + 1/30 = −1/30', 'v = −30 cm (real, inverted)'],
    formula: '1/v + 1/u = 1/f',
    units: { image_distance: 'cm' },
  },
  {
    id: 'mir_board_002',
    complexity: 'board',
    question: 'A convex mirror has focal length 20 cm. An object is 40 cm in front. Find image distance.',
    given: { u: -40, f: 20 },
    find: ['image_distance'],
    answer: { image_distance: 13.33 },
    tolerance: 3,
    hints: ['Convex mirror: f = +20 cm', '1/v = 1/f − 1/u = 1/20 − 1/(−40) = 1/20 + 1/40 = 3/40', 'v = +13.33 cm (virtual)'],
    formula: '1/v + 1/u = 1/f  (convex: f positive)',
    units: { image_distance: 'cm' },
  },
  {
    id: 'mir_board_003',
    complexity: 'board',
    question: 'Find the magnification when object is at C (centre of curvature) for a concave mirror of f = 20 cm.',
    given: { f: 20 },
    find: ['magnification'],
    answer: { magnification: -1 },
    tolerance: 2,
    hints: ['Object at C means u = 2f = −40 cm', 'Image also at C: v = −40 cm', 'm = −v/u = −(−40)/(−40) = −1'],
    formula: 'm = −v/u',
    units: { magnification: '' },
  },
  // JEE MAIN
  {
    id: 'mir_jee_main_001',
    complexity: 'jee_main',
    question: 'An object 2 cm tall is placed 20 cm in front of a concave mirror of f = 15 cm. Find the image height.',
    given: { h_obj: 2, u: -20, f: -15 },
    find: ['image_height'],
    answer: { image_height: -6 },
    tolerance: 3,
    hints: [
      '1/v = 1/f − 1/u = −1/15 + 1/20 = (−4+3)/60 = −1/60, so v = −60 cm',
      'm = −v/u = −(−60)/(−20) = −3',
      'h_image = m × h_obj = −3 × 2 = −6 cm (inverted)',
    ],
    formula: 'h_image = (−v/u) × h_obj',
    units: { image_height: 'cm' },
  },
  {
    id: 'mir_jee_main_002',
    complexity: 'jee_main',
    question: 'A concave mirror produces a virtual image 3× the object size. If f = 30 cm, find the object distance.',
    given: { m: 3, f: -30 },
    find: ['object_distance'],
    answer: { object_distance: -20 },
    tolerance: 3,
    hints: [
      'Virtual image → m = +3 (same side as object for mirror)',
      'm = −v/u = 3 → v = −3u',
      '1/(−3u) + 1/u = 1/(−30) → −1/3u + 1/u = −1/30 → 2/3u = −1/30 → u = −20 cm',
    ],
    formula: 'Combine m = −v/u with mirror formula',
    units: { object_distance: 'cm' },
  },
  {
    id: 'mir_jee_main_003',
    complexity: 'jee_main',
    question: 'A driver sees a car 100 m behind in a convex rear-view mirror of radius 2 m. Where is the image?',
    given: { u: -100, R: 2 },
    find: ['image_distance'],
    answer: { image_distance: 0.99 },
    tolerance: 3,
    hints: ['f = R/2 = +1 m', '1/v = 1/f − 1/u = 1/1 − 1/(−100) = 1 + 0.01 = 1.01', 'v ≈ +0.99 m ≈ 99 cm behind mirror'],
    formula: '1/v + 1/u = 1/f;  f = R/2',
    units: { image_distance: 'm' },
  },
  // JEE ADVANCED
  {
    id: 'mir_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'An object moves at 2 cm/s toward a concave mirror of f = 20 cm. Find the speed of the image when object is at 30 cm.',
    given: { v_obj: 2, u: -30, f: -20 },
    find: ['image_speed'],
    answer: { image_speed: 8 },
    tolerance: 4,
    hints: [
      'Differentiate: dv/dt = −(v/u)² × du/dt',
      'First find v: 1/v = 1/f − 1/u = −1/20 + 1/30 = −1/60 → v = −60 cm',
      'dv/dt = −(60/30)² × 2 = −4 × 2 = −8 cm/s (speed = 8 cm/s)',
    ],
    formula: 'dv/dt = −(v/u)² × du/dt  (velocity of image)',
    units: { image_speed: 'cm/s' },
  },
  {
    id: 'mir_jee_adv_002',
    complexity: 'jee_advanced',
    question: 'A concave mirror of f = 10 cm faces a plane mirror 30 cm away. A point object is 15 cm from the concave mirror on the axis. Where does the final image after both reflections form?',
    given: { f: -10, u: -15, d: 30 },
    find: ['final_image_position'],
    answer: { final_image_position: -19 },
    tolerance: 4,
    hints: [
      'First reflection (concave): 1/v = 1/(−10) − 1/(−15) = −1/10+1/15 = −1/30 → v = −30 cm',
      'This image is 30 cm behind concave mirror, coinciding with plane mirror surface',
      'Plane mirror: object at surface → image at surface of plane mirror → 30 cm from concave mirror → acts as object at 30 cm',
      'Second reflection (concave): u = −30, f = −10 → 1/v = −1/10 + 1/30 = −1/15 → v = −15 cm before plane mirror, i.e. 30−15=15 in front... track carefully',
    ],
    formula: 'Apply mirror formula twice (once per reflection)',
    units: { final_image_position: 'cm' },
  },
  {
    id: 'mir_jee_adv_003',
    complexity: 'jee_advanced',
    question: 'An equiconvex lens (n=1.5, R=20cm) has one surface silvered. Acting as a mirror, find its equivalent focal length.',
    given: { n: 1.5, R: 20 },
    find: ['f_eq'],
    answer: { f_eq: 10 },
    tolerance: 3,
    hints: [
      'Equivalent mirror: 1/F = 1/f_mirror + 2/f_lens',
      'f_mirror = R/2 = 10 cm (silvered surface, R=20)',
      'f_lens = R/(2(n−1)) = 20/(2×0.5) = 20 cm; 1/F = 1/10 + 2/20 = 2/10 → F = 10 cm',
    ],
    formula: '1/F_eq = 1/f_mirror + 2/f_refraction',
    units: { f_eq: 'cm' },
  },
]
