import { PuzzleConfig } from '../types'

export const PENDULUM_PUZZLES: PuzzleConfig[] = [
  // BOARD
  {
    id: 'pend_board_001',
    complexity: 'board',
    question: 'A simple pendulum has length 1 m. Find its time period on Earth (g = 9.8 m/s²).',
    given: { L: 1, g: 9.8 },
    find: ['period'],
    answer: { period: 2.007 },
    tolerance: 3,
    hints: ['T = 2π√(L/g)', 'T = 2π√(1/9.8)', 'T ≈ 2.00 s'],
    formula: 'T = 2π√(L/g)',
    units: { period: 's' },
  },
  {
    id: 'pend_board_002',
    complexity: 'board',
    question: 'A pendulum has time period 2 s. Find its length (g = 9.8 m/s²).',
    given: { T: 2, g: 9.8 },
    find: ['length'],
    answer: { length: 0.993 },
    tolerance: 3,
    hints: ['T = 2π√(L/g) → L = g(T/2π)²', 'L = 9.8 × (2/2π)²', 'L ≈ 0.993 m'],
    formula: 'L = g(T/2π)²',
    units: { length: 'm' },
  },
  {
    id: 'pend_board_003',
    complexity: 'board',
    question: 'A pendulum of length 25 cm oscillates. Find frequency (g = 9.8 m/s²).',
    given: { L: 0.25, g: 9.8 },
    find: ['frequency'],
    answer: { frequency: 0.995 },
    tolerance: 3,
    hints: ['f = 1/T = (1/2π)√(g/L)', 'f = (1/2π)√(9.8/0.25)', 'f ≈ 0.995 Hz'],
    formula: 'f = (1/2π)√(g/L)',
    units: { frequency: 'Hz' },
  },
  // JEE MAIN
  {
    id: 'pend_jee_main_001',
    complexity: 'jee_main',
    question: 'A pendulum has period T on Earth. What is its period on Moon where g_moon = g/6?',
    given: { g_ratio: 6 },
    find: ['period_ratio'],
    answer: { period_ratio: 2.449 },
    tolerance: 3,
    hints: [
      'T ∝ √(1/g), so T_moon/T_earth = √(g_earth/g_moon)',
      'T_moon = T√6',
      '√6 ≈ 2.449',
    ],
    formula: 'T_moon = T_earth × √(g_earth/g_moon)',
    units: { period_ratio: '' },
  },
  {
    id: 'pend_jee_main_002',
    complexity: 'jee_main',
    question: 'A seconds pendulum (T = 2 s) is taken to a height h above Earth where g reduces by 2%. Find the new period.',
    given: { T: 2, g_reduction_pct: 2 },
    find: ['new_period'],
    answer: { new_period: 2.02 },
    tolerance: 2,
    hints: [
      'T ∝ 1/√g, so ΔT/T = −(1/2)(Δg/g)',
      'g reduces by 2%: Δg/g = −0.02',
      'ΔT = T × 0.01 = 0.02 s → T_new = 2.02 s',
    ],
    formula: 'T_new ≈ T(1 + 0.01) for 2% drop in g',
    units: { new_period: 's' },
  },
  {
    id: 'pend_jee_main_003',
    complexity: 'jee_main',
    question: 'The time period of a pendulum clock is 2 s at the equator. How many seconds will it lose per day if taken to the North Pole where g is 0.5% larger?',
    given: { g_increase_pct: 0.5 },
    find: ['seconds_lost'],
    answer: { seconds_lost: 216 },
    tolerance: 3,
    hints: [
      'ΔT/T = −(1/2)(Δg/g) = −0.0025, so ΔT = −0.005 s per oscillation',
      'Number of oscillations per day = 86400/2 = 43200',
      'Total lost = 43200 × 0.005 = 216 s',
    ],
    formula: 'Lost per day = (ΔT/T) × 86400/2 × 86400',
    units: { seconds_lost: 's' },
  },
  // JEE ADVANCED
  {
    id: 'pend_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A pendulum of length L hangs from the ceiling of an elevator accelerating upward with acceleration a. Find the time period.',
    given: { L: 1, a: 2, g: 9.8 },
    find: ['period'],
    answer: { period: 1.826 },
    tolerance: 3,
    hints: [
      'Effective g_eff = g + a (upward acceleration increases effective gravity)',
      'g_eff = 9.8 + 2 = 11.8 m/s²',
      'T = 2π√(L/g_eff) = 2π√(1/11.8) ≈ 1.826 s',
    ],
    formula: 'T = 2π√(L/(g+a))',
    units: { period: 's' },
  },
  {
    id: 'pend_jee_adv_002',
    complexity: 'jee_advanced',
    question: 'A pendulum of length L₁ has the same time period as one of length L₂ when both are measured at different locations. If g₁ = 9.8 m/s² and L₁ = 1 m, L₂ = 1.02 m, find g₂.',
    given: { L1: 1, L2: 1.02, g1: 9.8 },
    find: ['g2'],
    answer: { g2: 9.996 },
    tolerance: 3,
    hints: [
      'Equal periods: √(L₁/g₁) = √(L₂/g₂)',
      'g₂/g₁ = L₂/L₁',
      'g₂ = 9.8 × 1.02 ≈ 9.996 m/s²',
    ],
    formula: 'g₂ = g₁ × (L₂/L₁)',
    units: { g2: 'm/s²' },
  },
  {
    id: 'pend_jee_adv_003',
    complexity: 'jee_advanced',
    question: 'A pendulum makes 200 oscillations in 200 s at the surface of Earth. At depth d = R/2 (R = Earth radius), g_depth = g(1 − d/R). How many oscillations in 200 s at that depth?',
    given: { n_surface: 200, d_over_R: 0.5 },
    find: ['n_depth'],
    answer: { n_depth: 141 },
    tolerance: 3,
    hints: [
      'g_depth = g(1 − 0.5) = 0.5g',
      'T_depth = T_surface × √(g/g_depth) = T × √2',
      'Oscillations at depth = 200/√2 ≈ 141',
    ],
    formula: 'n_depth = n × √(g_depth/g)',
    units: { n_depth: '' },
  },
]
