import { PuzzleConfig } from '../types'

export const ROLLING_PUZZLES: PuzzleConfig[] = [
  {
    id: 'roll_board_001',
    complexity: 'board',
    question: 'A solid sphere rolls without slipping down a 30° incline of height 2 m. Find the velocity at the bottom (g=10 m/s²). Use energy conservation with rotational KE.',
    given: { angle: 30, h: 2, g: 10 },
    find: ['velocity'],
    answer: { velocity: 5.35 },
    tolerance: 4,
    hints: [
      'Energy: mgh = ½mv² + ½Iω² ; for solid sphere I=2/5 mr², and ω=v/r',
      'mgh = ½mv²(1 + 2/5) = 7/10 mv²',
      'v = √(10gh/7) = √(10×10×2/7) ≈ 5.35 m/s',
    ],
    formula: 'v = √(10gh/7)  [solid sphere rolling]',
    units: { velocity: 'm/s' },
  },
  {
    id: 'roll_board_002',
    complexity: 'board',
    question: 'A hollow cylinder (I = mr²) rolls from rest down a 5 m high ramp. Find the speed at the bottom (g=10).',
    given: { h: 5, g: 10 },
    find: ['velocity'],
    answer: { velocity: 7.07 },
    tolerance: 4,
    hints: [
      'Energy: mgh = ½mv² + ½Iω² = ½mv² + ½mr²(v/r)² = mv²',
      'v² = gh → v = √(gh) = √(10×5) = √50 ≈ 7.07 m/s',
    ],
    formula: 'v = √(gh) for hollow cylinder',
    units: { velocity: 'm/s' },
  },
  {
    id: 'roll_jee_main_001',
    complexity: 'jee_main',
    question: 'A solid cylinder of mass 3 kg and radius 0.1 m rolls without slipping on a horizontal surface. If its linear speed is 4 m/s, find its total KE.',
    given: { m: 3, r: 0.1, v: 4 },
    find: ['KE_total'],
    answer: { KE_total: 36 },
    tolerance: 3,
    hints: [
      'KE_rot = ½Iω² = ½(mr²/2)(v/r)² = mv²/4',
      'KE_trans = ½mv² = ½×3×16 = 24 J',
      'KE_total = 24 + 12 = 36 J',
    ],
    formula: 'KE = ¾mv²  [solid cylinder]',
    units: { KE_total: 'J' },
  },
  {
    id: 'roll_jee_main_002',
    complexity: 'jee_main',
    question: 'A sphere rolls up an incline. If v = 7 m/s at the bottom, find the height reached (g=10).',
    given: { v: 7, g: 10 },
    find: ['height'],
    answer: { height: 3.43 },
    tolerance: 3,
    hints: [
      '7/10 mv² = mgh  (sphere rolling)',
      'h = 7v²/(10g) = 7×49/100 = 3.43 m',
    ],
    formula: 'h = 7v²/(10g)',
    units: { height: 'm' },
  },
  {
    id: 'roll_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A disc and a sphere of equal mass m and radius r start from rest and roll down the same height h. Find the ratio of their speeds at the bottom.',
    given: { h: 1, g: 10 },
    find: ['v_ratio'],
    answer: { v_ratio: 1.069 },
    tolerance: 3,
    hints: [
      'Disc: v_d = √(4gh/3);  Sphere: v_s = √(10gh/7)',
      'Ratio = v_sphere/v_disc = √(10/7 × 3/4) = √(30/28) ≈ 1.035',
      'Actually ratio = √(30/28) ≈ 1.035 — check which is faster',
    ],
    formula: 'v = √(2gh/(1+I/mr²))',
    units: { v_ratio: '' },
  },
]
