import { PuzzleConfig } from '../types'

export const WORK_ENERGY_PUZZLES: PuzzleConfig[] = [
  {
    id: 'we_board_001',
    complexity: 'board',
    question: 'A 5 kg block falls from a height of 10 m. Find its kinetic energy just before hitting the ground (g=10 m/s²).',
    given: { m: 5, h: 10, g: 10 },
    find: ['KE'],
    answer: { KE: 500 },
    tolerance: 3,
    hints: ['KE = mgh = 5×10×10 = 500 J (energy conservation)'],
    formula: 'KE = mgh',
    units: { KE: 'J' },
  },
  {
    id: 'we_board_002',
    complexity: 'board',
    question: 'A 10 N force is applied over a displacement of 4 m at 60° to the displacement. Find the work done.',
    given: { F: 10, d: 4, theta: 60 },
    find: ['work'],
    answer: { work: 20 },
    tolerance: 3,
    hints: ['W = Fd cosθ = 10×4×cos60° = 10×4×0.5 = 20 J'],
    formula: 'W = Fd cosθ',
    units: { work: 'J' },
  },
  {
    id: 'we_jee_main_001',
    complexity: 'jee_main',
    question: 'A variable force F = 3x² (N) acts on a body. Find the work done as the body moves from x=1m to x=3m.',
    given: { a: 1, b: 3 },
    find: ['work'],
    answer: { work: 26 },
    tolerance: 3,
    hints: [
      'W = ∫F dx = ∫₁³ 3x² dx',
      '= [x³]₁³ = 27 − 1 = 26 J',
    ],
    formula: 'W = ∫F dx',
    units: { work: 'J' },
  },
  {
    id: 'we_jee_main_002',
    complexity: 'jee_main',
    question: 'A spring of k=200 N/m is compressed by 0.1 m. A 0.5 kg mass is placed against it. Find the speed of the mass when the spring returns to natural length (ignore gravity along spring).',
    given: { k: 200, x: 0.1, m: 0.5 },
    find: ['speed'],
    answer: { speed: 2.0 },
    tolerance: 3,
    hints: [
      '½kx² = ½mv²',
      'v = x√(k/m) = 0.1×√(200/0.5) = 0.1×20 = 2 m/s',
    ],
    formula: 'v = x√(k/m)',
    units: { speed: 'm/s' },
  },
  {
    id: 'we_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'A body of mass 2 kg starts from rest and is acted on by F=(4+0.1x) N along its motion. Find the KE after moving 10 m.',
    given: { m: 2, F0: 4, k: 0.1, d: 10 },
    find: ['KE'],
    answer: { KE: 45 },
    tolerance: 3,
    hints: [
      'W = ∫₀¹⁰(4+0.1x)dx = [4x + 0.05x²]₀¹⁰',
      '= 40 + 5 = 45 J',
      'KE = W = 45 J (starts from rest)',
    ],
    formula: 'W = ∫F dx  →  KE',
    units: { KE: 'J' },
  },
  {
    id: 'we_jee_adv_002',
    complexity: 'jee_advanced',
    question: 'Power delivered by a constant force F=15 N to a 3 kg body initially at rest after t=4 s (all along direction of motion). Find instantaneous power at t=4s.',
    given: { F: 15, m: 3, t: 4 },
    find: ['power'],
    answer: { power: 300 },
    tolerance: 3,
    hints: [
      'a = F/m = 5 m/s²',
      'v at t=4s = at = 20 m/s',
      'P = Fv = 15×20 = 300 W',
    ],
    formula: 'P = Fv = F(at) = F²t/m',
    units: { power: 'W' },
  },
]
