import { PuzzleConfig } from '../types'

export const YDSE_PUZZLES: PuzzleConfig[] = [
  // BOARD
  {
    id: 'ydse_board_001',
    complexity: 'board',
    question: 'In a YDSE experiment, slit separation d = 1 mm, screen distance D = 1 m, λ = 600 nm. Find fringe width β.',
    given: { d: 1e-3, D: 1, lambda: 600e-9 },
    find: ['fringe_width'],
    answer: { fringe_width: 0.6 },
    tolerance: 3,
    hints: ['β = λD/d', 'β = 600×10⁻⁹ × 1 / 10⁻³', 'β = 0.6 mm = 6×10⁻⁴ m'],
    formula: 'β = λD/d',
    units: { fringe_width: 'mm' },
  },
  {
    id: 'ydse_board_002',
    complexity: 'board',
    question: 'Bright fringes in YDSE are 1.2 mm apart. If D = 2 m and d = 1 mm, find the wavelength.',
    given: { beta: 1.2e-3, D: 2, d: 1e-3 },
    find: ['wavelength'],
    answer: { wavelength: 600 },
    tolerance: 3,
    hints: ['λ = βd/D', 'λ = 1.2×10⁻³ × 10⁻³ / 2', 'λ = 6×10⁻⁷ m = 600 nm'],
    formula: 'λ = βd/D',
    units: { wavelength: 'nm' },
  },
  {
    id: 'ydse_board_003',
    complexity: 'board',
    question: 'Find the position of the 3rd bright fringe from centre in YDSE: d=0.5mm, D=1m, λ=500nm.',
    given: { d: 0.5e-3, D: 1, lambda: 500e-9, n: 3 },
    find: ['y3'],
    answer: { y3: 3 },
    tolerance: 3,
    hints: ['y_n = nλD/d', 'y₃ = 3 × 500×10⁻⁹ × 1 / 0.5×10⁻³', 'y₃ = 3×10⁻³ m = 3 mm'],
    formula: 'y_n = nλD/d',
    units: { y3: 'mm' },
  },
  // JEE MAIN
  {
    id: 'ydse_jee_main_001',
    complexity: 'jee_main',
    question: 'In YDSE, the screen is moved closer by 25 cm. The fringe width decreases by 0.1 mm. If d = 1 mm, find λ.',
    given: { delta_D: 0.25, delta_beta: 0.1e-3, d: 1e-3 },
    find: ['wavelength'],
    answer: { wavelength: 400 },
    tolerance: 3,
    hints: [
      'Δβ = λ × ΔD / d',
      'λ = Δβ × d / ΔD = 0.1×10⁻³ × 10⁻³ / 0.25',
      'λ = 4×10⁻⁷ m = 400 nm',
    ],
    formula: 'λ = Δβ·d/ΔD',
    units: { wavelength: 'nm' },
  },
  {
    id: 'ydse_jee_main_002',
    complexity: 'jee_main',
    question: 'YDSE is performed with two wavelengths 600 nm and 400 nm. At what minimum distance from centre do their bright fringes coincide? (d=1mm, D=1m)',
    given: { lambda1: 600e-9, lambda2: 400e-9, d: 1e-3, D: 1 },
    find: ['coincidence_y'],
    answer: { coincidence_y: 1.2 },
    tolerance: 3,
    hints: [
      'n₁λ₁ = n₂λ₂ → n₁×600 = n₂×400 → n₁/n₂ = 2/3 → n₁=2, n₂=3',
      'y = n₁λ₁D/d = 2×600×10⁻⁹×1/10⁻³',
      'y = 1.2×10⁻³ m = 1.2 mm',
    ],
    formula: 'Find LCM of λ₁ and λ₂ to get coincidence',
    units: { coincidence_y: 'mm' },
  },
  {
    id: 'ydse_jee_main_003',
    complexity: 'jee_main',
    question: 'In YDSE, one slit is covered with a thin glass plate (μ=1.5, t=0.01mm). By how many fringes does the central maximum shift? (λ=500nm)',
    given: { mu: 1.5, t: 1e-5, lambda: 500e-9 },
    find: ['fringe_shift'],
    answer: { fringe_shift: 10 },
    tolerance: 3,
    hints: [
      'Extra path = (μ−1)t = 0.5 × 10⁻⁵ = 5×10⁻⁶ m',
      'Fringe shift = extra path / λ = 5×10⁻⁶ / 500×10⁻⁹',
      'Shift = 10 fringes',
    ],
    formula: 'shift = (μ−1)t/λ',
    units: { fringe_shift: 'fringes' },
  },
  // JEE ADVANCED
  {
    id: 'ydse_jee_adv_001',
    complexity: 'jee_advanced',
    question: 'In a YDSE setup submerged in water (μ=4/3), fringe width is observed to be 0.9 mm. What was it in air? (same d, D, λ)',
    given: { beta_water: 0.9, mu_water: 1.333 },
    find: ['beta_air'],
    answer: { beta_air: 1.2 },
    tolerance: 3,
    hints: [
      'In water, λ_eff = λ/μ, so β_water = λD/(μd)',
      'β_air = μ × β_water = 1.333 × 0.9',
      'β_air = 1.2 mm',
    ],
    formula: 'β_air = μ_water × β_water',
    units: { beta_air: 'mm' },
  },
  {
    id: 'ydse_jee_adv_002',
    complexity: 'jee_advanced',
    question: "In a modified YDSE, a mirror replaces one of the slits (Lloyd\u2019s mirror). If original fringe width \u03b2 = 1 mm, what is the shift of the central dark fringe?",
    given: { beta: 1 },
    find: ['shift'],
    answer: { shift: 0.5 },
    tolerance: 3,
    hints: [
      "In Lloyd's mirror, the reflected beam undergoes a phase shift of π",
      'This shifts the pattern by β/2 — bright and dark swap',
      'Central dark fringe shifts by β/2 = 0.5 mm from the geometric centre',
    ],
    formula: "Shift = β/2 (Lloyd's mirror phase inversion)",
    units: { shift: 'mm' },
  },
  {
    id: 'ydse_jee_adv_003',
    complexity: 'jee_advanced',
    question: 'YDSE uses slits of widths w₁ and w₂. The intensity ratio I_max/I_min = 9. Find ratio w₁/w₂ (assume amplitude ∝ √width).',
    given: { intensity_ratio: 9 },
    find: ['width_ratio'],
    answer: { width_ratio: 4 },
    tolerance: 3,
    hints: [
      'a ∝ √w, so a₁/a₂ = √(w₁/w₂)',
      'I_max/I_min = (a₁+a₂)²/(a₁−a₂)² = 9 → (a₁+a₂)/(a₁−a₂) = 3',
      'Solving: a₁/a₂ = 2, so w₁/w₂ = 4',
    ],
    formula: 'I_max/I_min = [(√w₁+√w₂)/(√w₁−√w₂)]²',
    units: { width_ratio: '' },
  },
]
